#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TVOS_WORKSPACE="$ROOT_DIR/tvosApp/NuvioTV.xcworkspace"
TVOS_SCHEME="NuvioTV"
OUTPUT_DIR="$ROOT_DIR/build-ipa"
ARCHIVE_DIR="$(mktemp -d)/NuvioTV.xcarchive"

cleanup() {
  rm -rf "$(dirname "$ARCHIVE_DIR")"
}
trap cleanup EXIT

# The Xcode project is generated by Tuist and is not tracked in git.
echo "==> Generating Xcode project with Tuist..."
if command -v tuist >/dev/null 2>&1; then
  (cd "$ROOT_DIR/tvosApp" && tuist generate --no-open)
elif command -v mise >/dev/null 2>&1; then
  (cd "$ROOT_DIR/tvosApp" && mise exec -- tuist generate --no-open)
else
  echo "error: tuist not found. Install it with 'mise install' (see mise.toml)." >&2
  exit 1
fi

# tvosApp/Project.swift pins MARKETING_VERSION (3.3.4) and CURRENT_PROJECT_VERSION
# (65); upstream overrides them at build time for each release instead of
# committing the bump, so a nightly would otherwise be stamped 3.3.4. Read the
# newest release note this tree carries and build that version.
RELEASE_VERSION="$(python3 - "$ROOT_DIR/release" <<'PY'
import pathlib, re, sys

best = ()
for path in pathlib.Path(sys.argv[1]).glob("tvos-beta-*.md"):
    match = re.fullmatch(r"tvos-beta-(\d+)\.(\d+)(?:\.(\d+))?", path.stem)
    if match:
        parts = tuple(int(value) for value in match.groups(default="0"))
        best = max(best, parts)
print(".".join(str(part) for part in best) if best else "")
PY
)"

VERSION_OVERRIDE=()
if [[ -n "$RELEASE_VERSION" ]]; then
  VERSION_OVERRIDE+=("MARKETING_VERSION=$RELEASE_VERSION")
  echo "==> Building app version ${RELEASE_VERSION} (from release notes)"
else
  echo "warning: no release/tvos-beta-*.md found; keeping the version pinned in tvosApp/Project.swift" >&2
fi

echo "==> Archiving ${TVOS_SCHEME} for tvOS (Release, unsigned)..."
xcodebuild archive \
  -workspace "$TVOS_WORKSPACE" \
  -scheme "$TVOS_SCHEME" \
  -configuration Release \
  -destination 'generic/platform=tvOS' \
  -archivePath "$ARCHIVE_DIR" \
  CODE_SIGN_IDENTITY="" \
  CODE_SIGNING_REQUIRED=NO \
  CODE_SIGNING_ALLOWED=NO \
  CODE_SIGN_ENTITLEMENTS="" \
  "${VERSION_OVERRIDE[@]+"${VERSION_OVERRIDE[@]}"}" \
  -quiet

APP_PATH="$ARCHIVE_DIR/Products/Applications/NuvioTV.app"
if [[ ! -d "$APP_PATH" ]]; then
  echo "Error: Archive failed, NuvioTV.app not found at $APP_PATH" >&2
  exit 1
fi

VERSION=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$APP_PATH/Info.plist" 2>/dev/null || echo "latest")
BUILD=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "$APP_PATH/Info.plist" 2>/dev/null || echo "latest")

echo "==> Packaging unsigned IPA for version ${VERSION} (${BUILD})..."
rm -rf "$OUTPUT_DIR/Payload" "$OUTPUT_DIR"/*.ipa
mkdir -p "$OUTPUT_DIR/Payload"
cp -R "$APP_PATH" "$OUTPUT_DIR/Payload/"

(
  cd "$OUTPUT_DIR"
  zip -qry "NuvioTV-unsigned.ipa" Payload
  cp "NuvioTV-unsigned.ipa" "NuvioTV-${VERSION}-unsigned-release.ipa"
)

printf 'version=%s\nbuild=%s\n' "$VERSION" "$BUILD" > "$OUTPUT_DIR/build-metadata.env"

echo "==> Unsigned IPA created successfully:"
ls -lh "$OUTPUT_DIR"/*.ipa
